# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
    ]
