# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredimage',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filteredimage',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filteredimage',
            name='image',
            field=models.ImageField(upload_to='editedphotos'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
