# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_image_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
