# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160707_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredimage',
            name='effect',
            field=models.CharField(default=datetime.datetime(2016, 7, 25, 10, 55, 22, 375885, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
