# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_filteredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredimage',
            name='image',
            field=models.ImageField(upload_to='editedphotos/'),
        ),
        migrations.AlterField(
            model_name='filteredimage',
            name='originalimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='main.Image'),
        ),
    ]
