# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160630_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredimage',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
